ktor:
    application:
        modules:
            - rebel.ApplicationKt.module
    deployment:
        port: 8080
        watch:
            - classes
            - resources

    development: true
